[package]
name = "apifuzz"
version = "0.1.0"
authors = ["Tom Fogal <tfogal@sci.utah.edu>"]
build = "build.rs"

[dependencies]
rand = "0.3"

[dependencies.lalrpop-util]
version = "0.12.5"

[build-dependencies.lalrpop]
version = "0.12.5"
